style/login 페이지, 연결하기 위해 main, user 안의 url.py 파일 주소 연결, main 내의 views…
CalmCrews/Relanz pull request #40
Opened 2023-06-19 13:40 UTC by LeLu815

1. style/login 페이지 
2. 연결하기 위해 main, user 안의 url.py 파일 주소 연결 
3. main 내의 views 파일에 로그인 함수 간단생성

2023-06-19 13:45 UTC, imjanghyeok reviewed
우림누나가 승인하면 승인할게용

2023-06-19 13:45 UTC, imjanghyeok commented on relanz/main/urls.py
> +    path('login/', views.login, name="login"),
주석달아주세요

2023-06-19 13:45 UTC, imjanghyeok commented on relanz/main/views.py
> -    return render(request, 'main/home.html')
이런 거 있으면 커밋에는 없어도, PR comment나 주석으로 달아주시면 감사하겠습니다.

2023-06-19 15:01 UTC, KRimwoo requested changes

2023-06-19 15:01 UTC, KRimwoo commented on relanz/templates/user/signin.html
> +        <input type="text" placeholder="비밀번호 입력" id="password" class="password-input">
비밀번호 입력할 때 문자 숨기는 거 가능할까요? 약간의 js 추가... :)

2023-06-20 02:25 UTC, KRimwoo approved these changes

2023-06-20 02:25 UTC, KRimwoo commented on relanz/templates/user/signin.html
> -    {% csrf_token %}
csrf 토큰 잘 확인합시당!

2023-06-20 02:29 UTC, imjanghyeok approved these changes

2023-06-20 02:29 UTC, merged